name: "pr2changelog"
author: "Andrés Riquelme <andresfranco.rs@gmail.com>"
description: "Generates a changelog when a PR is merged based on a short description given by the PR author."
inputs:
    categories:
        description: "List of categories the listed changes should have separated by ';'. note that the search is
        case-sensitive and if you declare this input, pr2changelog won't log lines without category."
        required: false
        default: ""
    change_token:
        description: "Regex will search for this string to find change lines. Default is CL:"
        required: false
        default: "CL"
    file_name:
        description: "What's the changelog file's name including extension (recommended .md)"
        required: false
        default: "CHANGELOG.md"
outputs:
    generated_changelog:
        description: "If true, it means we generated a changelog and need to push changes"
    changelog_content:
        description: "The actual content of the generated changelog"
runs:
    using: 'docker'
    image: 'Dockerfile'
branding:
    icon: 'edit'
    color: 'purple'